### ISSUE TITLE
linter-swagger not working

### ISSUE THREAD

**Issue by RiaanLab** [AtomLinter/linter-swagger#14]
I have tried to get linter-swagger to lint swagger V2 files in Atom but it does not seem to work. I installed linter-swagger and linter via the Atom package installer via the command line (apm) and via the Atom GUI.

It does not lint files at all.  I did also install linter-js-yaml to check if the rest of my installation works. When I open files with the *.yaml extension the linter-js-yaml lints perfectly. (This is as per the linter-js.yaml docs)

I can not see if the linter-swagger needs any special file naming convention when opening files to lint as there is no documentation. 

If you could tell me what I am doing wrong I will write the install docs, based on my experience,  for you.

**Comment by Arcanemagus** [comment]
Looks like this is only running if `/"?swagger"?\s*:\s*"\d+\.\d+"/g` passes (IE: a `swagger: "x.y"` key exists).

As none of the examples [here](http://swagger.io/specification/) show that, I'm guessing that it hasn't been updated to account for that?

@spoike do you know what needs to be done to fix this? I have no experience with this.

**Comment by RiaanLab** [comment]
Great, we got ii working. Thanks Arcanemagus 

We will write a howto on getting things up and running. Big Thank You to the contributors for their work.

**Comment by Arcanemagus** [comment]
It looks like the readme here is quite barren, a PR fixing it up would be nice :wink:

@RiaanLab You wouldn't happen to be interested in helping to maintain this, would you?

@spoike Are you still interested in maintaining this? Haven't gotten a response from you on issues for a while now...

**Comment by RiaanLab** [comment]
Yip, will definitely help in supporting it.

Will write the install howto. Anything that I should and should not do?

Riaan Labuschagne

riaan@fullfacing.com
Cel: +2783 4444148
Tel: +2721 5213000
Fax: +2721 521 3001
www.fullfacing.com

**Comment by Arcanemagus** [comment]
Invited you as a collaborator here :tada:

The first thing I would do if I were you would be to deal with https://github.com/AtomLinter/linter-swagger/issues/3. Once that is implemented we can work on getting CI builds running which will ensure the plugin is working as expected.

If you have any questions feel free to tag myself or @steelbrain, and if you were interested there is a #linter-plugin-dev channel on Atom's Slack instance.

**Comment by RiaanLab** [comment]
Thanks,

I am starting with the README as I had issues getting linter-swagger to 
validate files in Atom. Will fork and update the README.md

Riaan Labuschagne

riaan@fullfacing.com
Cel: +2783 4444148
Tel: +2721 5213000
Fax: +2721 521 3001
www.fullfacing.com

**Comment by RiaanLab** [comment]
@steelbrain <https://github.com/steelbrain>

What license version do we have to use for linter-swagger?

Riaan Labuschagne

riaan@fullfacing.com
Cel: +2783 4444148
Tel: +2721 5213000
Fax: +2721 521 3001
www.fullfacing.com

**Comment by Arcanemagus** [comment]
Btw, it's better to just do a branch on the main repo, that way others can contribute as well if needed.

**Comment by Arcanemagus** [comment]
The License is MIT: https://github.com/AtomLinter/linter-swagger/blob/v0.3.4/package.json#L12

**Comment by spoike** [comment]
FYI, regarding if the `swagger` field should be in or not: it SHOULD be in there as per spec linked above (under Schema / Fixed Fields). it is the first one listed and is also required. I use this as a hack, to avoid linting files that are JSON or YAML files but aren't Swagger files.

Judging by what was done for the README (see #15) I fixed the underlying issue with not supporting single quotes (that can be used in YAML files, which I was unaware of... sorry!).
