### ISSUE TITLE
Install Linter automatically

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-swagger#16]
Using the `npm` module `atom-package-deps` you can install `linter` automatically.

To do this you must:

1. Add `atom-package-deps` as a dependency in [`package.json`](https://github.com/AtomLinter/linter-xmllint/blob/v1.3.4/package.json#L13).
2. Specify your package dependencies like [this](https://github.com/AtomLinter/linter-xmllint/blob/v1.3.4/package.json#L21-L23).
3. Call the `install()` method with your package name in `activate()` like [this](https://github.com/AtomLinter/linter-xmllint/blob/v1.3.4/lib/init.coffee#L30).

**Comment by spoike** [comment]
I'll add these
