### ISSUE TITLE
Implement specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-swagger#3]
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

**Comment by spoike** [comment]
@Arcanemagus I've added a spec with some fixtures for "sanity check" of linter-swagger. If I need to add any CI config then I need help with that. Other than that, I guess it's done.

**Comment by Arcanemagus** [comment]
Awesome! That should help with the GreenKeeper PR spam :stuck_out_tongue:

It looks like @steelbrain already helped point you in the right direction for enabling CI, if you have any other questions though just ask!
