### ISSUE TITLE
save swagger yaml will cause error "Expected messages to be array, provided: object"

### ISSUE THREAD

**Issue by samuel-ye** [AtomLinter/linter-swagger#32]
atom 1.11.2
linter 1.11.18
linter-swagger 0.3.7
swagger-parser 4.0beta & 3.4.1

When saving swagger yaml files, Atom will prompt error "Expected messages to be array, provided: object at Object.module.Vaildate.messages"

It seems that lib/validator.js line 81 should return an array with [] closed.

**Comment by LobeTia** [comment]
I created a pull request for fixing this error
#33
