### ISSUE TITLE
OpenAPI3 ?

### ISSUE THREAD

**Issue by rgarrigue** [AtomLinter/linter-swagger#66]
Hello

I'ld just like to know if you intend to cover OpenAPI 3 one day ? 

Best regards,

**Comment by Arcanemagus** [comment]
Your question is better directed at [swagger-parser](https://www.npmjs.com/package/swagger-parser) as this is just a wrapper around that 😉.

**Comment by yemartin** [comment]
Can you reopen this @Arcanemagus ? swagger-parser now supports OpenAPI 3, since v5.0.0 which was released a couple of months ago ([CHANGELOG.md#v500-2018-05-25](https://github.com/BigstickCarpet/swagger-parser/blob/36fd8050c7596eafda6cfc11fbb73ab520358101/CHANGELOG.md#v500-2018-05-25)).

**Comment by Arcanemagus** [comment]
Looks like you're waiting on #63 then...

**Comment by Arcanemagus** [comment]
Published in v0.5.0, sorry about the delay!

On that note, if either of you are interested in helping maintain this just let me know 😉.
