### ISSUE TITLE
Support v2 Linter API

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-swagger#71]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

**Comment by vzamanillo** [comment]
@Arcanemagus, I am working on this, but tests are failing due to a unexpected swagger-parser errors

https://github.com/vzamanillo/linter-swagger/tree/v2-linter-api-support

**Comment by Arcanemagus** [comment]
Yeah, `master` is currently broken: https://travis-ci.org/AtomLinter/linter-swagger/builds/483157022

It broke sometime since 2018-12-30 and 2019-01-22, I haven't had time to look into this myself if you were interested in fixing it.

**Comment by vzamanillo** [comment]
> Yeah, `master` is currently broken: https://travis-ci.org/AtomLinter/linter-swagger/builds/483157022
> 
> It broke sometime since 2018-12-30 and 2019-01-22, I haven't had time to look into this myself if you were interested in fixing it.

Could you please put this "In progress"?
